---
sudo: required
services:
  - docker
install:
  - sudo pip install ansible==2.3.0
  - sudo pip install ansible-lint==3.4.10
  - sudo pip install molecule==2.19.0
  - sudo pip install docker
script: molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
