#!/bin/bash

# Exit immediately on error
set -e

echo "FROM geerlingguy/docker-${distro}-ansible:latest" > tests/Dockerfile

# Customize container
container_tag=${distro}:ansible
sudo docker build \
  --rm=true \
  --tag=${container_tag} tests

# Run container in detached state
id_file=$(mktemp)
sudo docker run \
  --detach \
  --volume="${PWD}":/etc/ansible/roles/role_under_test:ro \
  ${run_opts} \
  ${container_tag} ${init} > "${id_file}"
container_id="$(cat $id_file)"
echo "Container ID:" "${container_id}"

# Ansible syntax check.
sudo docker exec "${container_id}" \
  env TERM=xterm \
  ansible-playbook /etc/ansible/roles/role_under_test/tests/install.yml \
    --syntax-check

# Check that role installs successfully.
install_dir=/opt
sudo docker exec "${container_id}" \
  env TERM=xterm \
  ansible-playbook /etc/ansible/roles/role_under_test/tests/install.yml \
    --extra-vars "web100clt_install_dir=${install_dir}"

# Clean up
sudo docker stop "${container_id}"
sudo docker rm "${container_id}"
rm tests/Dockerfile

# Ansible lint check (outside of docker container).
ansible-lint tests/install.yml
