---
- name: install build tools for Debian
  apt:
    name: "{{ packages }}"
    state: installed
    update_cache: yes
  vars:
    packages:
      - automake
      - gcc
      - git
      - libssl-dev
      - make
      - openssl
      - subversion
  when: ansible_os_family == 'Debian'

- name: install build tools for RedHat
  package:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
      - automake
      - gcc
      - git
      - make
      - openssl
      - openssl-devel
      - subversion
      - tar
  when: ansible_os_family == 'RedHat'

- name: download jansson source
  unarchive:
    copy: no
    src: "http://www.digip.org/jansson/releases/jansson-{{ web100clt_jansson_version }}.tar.gz"
    dest: "{{ web100clt_temp_dir }}"

- name: build and install jansson from source
  command: "{{ item }}"
  args:
    chdir: "{{ web100clt_jansson_build_dir }}"
    creates: /usr/local/include/jansson.h
  with_items:
    - ./configure
    - make
    - make install

- name: get ndt source
  git:
    repo: https://github.com/ndt-project/ndt.git
    dest: "{{ web100clt_install_dir }}/ndt"
    version: "{{ web100clt_ndt_version }}"
  register: ndt_source

- name: build and install I2util from source
  command: "{{ item }}"
  args:
    chdir: "{{ web100clt_install_dir }}/ndt/I2util"
  with_items:
    - ./bootstrap.sh
    - ./configure
    - make
    - make install
  when: ndt_source.changed

- name: build NDT
  command: "{{ item }}"
  args:
    chdir: "{{ web100clt_install_dir }}/ndt"
  with_items:
    - ./bootstrap
    - ./configure
    - make
  when: ndt_source.changed

- name: build web100clt
  command: make web100clt
  args:
    chdir: "{{ web100clt_install_dir }}/ndt/src"
  when: ndt_source.changed
