FROM debian:8

ENV TERM=xterm

# Install dependencies.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       sudo python-simplejson \
    && rm -rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean
